version: '3'
services:

  cluster:
    build: .
    image: app-cluster
    working_dir: /opt/app
    ports:
      - '9000:9000'
    env_file:
      - .env
    volumes:
      - ./:/opt/app

  dynamodb:
    image: amazon/dynamodb-local:1.18.0
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:4.3.0
    restart: always
    ports:
      - '8001:8001'
    env_file:
      - .env
    depends_on:
      - dynamodb
